### ISSUE TITLE
你好，请问有训练的相关代码吗？

### ISSUE THREAD

**Issue by PnZheng** [limuhit/pseudocylindrical_convolution#1]

**Comment by limuhit** [comment]
We have the training codes and will release them soon. Currently, I am busy and working on the NSFC application. You may come back one month later to check the codes. If the codes still are unavailable, please remind me to release them.

**Comment by PnZheng** [comment]
Thank you for your speedy response.  
Hope you are doing well.

**Comment by PnZheng** [comment]
Hello，i have run the code in the test folder, but it show me "ImportError: cannot import name 'ChannelGroupConv' from 'PCONV_operator' ". Whether some code don't upload to github?

**Comment by limuhit** [comment]
This is something new in our future jobs.  We have removed it now. Try the new code.
