### ISSUE TITLE
您好，请问可以提供train代码吗？

### ISSUE THREAD

**Issue by zsevenj** [limuhit/pseudocylindrical_convolution#2]

**Comment by limuhit** [comment]
Please check the test folder. Run the trainDDP_Base.py to train the baseline model without entropy loss for initialization. Run the trainDDP_Full.py for training the whole model.  "run.sh" gives an example for training.

**Comment by zsevenj** [comment]
> Please check the test folder. Run the trainDDP_Base.py to train the baseline model without entropy loss for initialization. Run the trainDDP_Full.py for training the whole model. "run.sh" gives an example for training.

Thanks, Really appreciate your fast response!
